default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: order_tracking
  password: 123456

development:
  <<: *default
  database: order_tracking_development
test:
  <<: *default
  database: order_tracking_test
production:
  url: <%= ENV['DATABASE_URL'] %>